### PR TITLE
feat: remove header

### PR DESCRIPTION
**Pull request by Averethel**
The header was moved to [its own package](https://github.com/carforyou/carforyou-header-footer-pkg), with all projects migrated we can remove it from components

### CODE REVIEW

**Review by GutierrezGo — COMMENTED** [review]
What about the header.css?

**Comment by Averethel** [comment]
@GutierrezGo removed now, good point 👍

**Review by GutierrezGo — COMMENTED** [review]
Maybe the header values in tailwind.
They are 7 values.

**Comment by GutierrezGo** [comment]
> @GutierrezGo That's awkward but we still use those in the header package and without them, the header would be b0rked.
> They would eventually go away once we're ready to switch to CSS modules in packages, which @masone is looking into

I see, thank you for making clear this point.

**Review by GutierrezGo — APPROVED** [review]

**Review by masone — APPROVED** [review]

**Pull request merged**
