### PR TITLE
Tooltip

### PR DESCRIPTION
**Pull request by Marine-Berthier**
For this component I created only one story since it is now possible to play around with the tooltip's position and alignment in the Control pannel. If you think we still need to write a story for every position and alignment let me know

### CODE REVIEW

**Comment by ralucacril** [comment]
I think you are missing some stories.
Screenshot 2020-12-03 at 17 08 10

**Comment by Marine-Berthier** [comment]
@ralucacril yes, that's what I explained in the comment above. I am not sure but since it is now possible to play around with the tooltip's position and alignment in the Control pannel, do we still need the whole list ?

**Comment by ralucacril** [comment]
so so sorry, i missed your comment. 🙈

**Comment by ralucacril** [comment]
tbh for us might not be important to have them as a separate story. but maybe for designers could be important. might not hurt to ask Fred (he is on slack)  or Enrique if they would find the benefit of the story.

**Comment by Marine-Berthier** [comment]
@ralucacril Thanks Raluca, I will ask Enrique 👍

**Comment by Marine-Berthier** [comment]
@ralucacril According to Enrique there's no need to have the full list

**Review by ralucacril — APPROVED** [review]
thanks for checking with Enrique

**Pull request merged**
